#!/bin/sh
# Install a verified GitHub release without sudo or host package changes.
set -eu

fail() { printf 'install: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || fail "missing prerequisite: $1"; }

# Reject unsupported platforms before any network requests or filesystem changes.
need uname
os=$(uname -s) || fail 'cannot detect operating system'
[ "$os" = Linux ] || fail "unsupported operating system: $os (Linux required)"
arch=$(uname -m) || fail 'cannot detect architecture'
case "$arch" in
    x86_64) target=x86_64-unknown-linux-musl ;;
    aarch64|arm64) target=aarch64-unknown-linux-musl ;;
    *) fail "unsupported architecture: $arch (x86_64 or aarch64 required)" ;;
esac
for tool in curl tar sha256sum mktemp mkdir chmod cp mv rm; do need "$tool"; done

repo=https://github.com/MatthewScholefield/dockstride
tag=${DOCKSTRIDE_VERSION:-}
if [ -z "$tag" ]; then
    latest=$(curl -fsSL -o /dev/null -w '%{url_effective}' "$repo/releases/latest") \
        || fail 'cannot resolve the latest stable GitHub release'
    case "$latest" in
        */releases/tag/*) tag=${latest##*/} ;;
        *) fail "unexpected latest release URL: $latest" ;;
    esac
fi
case "$tag" in
    v[0-9]*) version=${tag#v} ;;
    *) fail 'release version must be a tag such as v0.1.0' ;;
esac
case "$version" in
    *[!0-9A-Za-z.+-]*) fail "invalid release version: $tag" ;;
esac

if [ -n "${DOCKSTRIDE_INSTALL_DIR:-}" ]; then
    install_dir=$DOCKSTRIDE_INSTALL_DIR
else
    [ -n "${HOME:-}" ] || fail 'HOME is unset; set DOCKSTRIDE_INSTALL_DIR'
    install_dir=$HOME/.local/bin
fi
case "$install_dir" in
    /*) ;;
    *) install_dir=$(pwd -P)/$install_dir ;;
esac
temp_root=${TMPDIR:-/tmp}
case "$temp_root" in
    /*) ;;
    *) temp_root=$(pwd -P)/$temp_root ;;
esac

temp=
pending=
cleanup() {
    if [ -n "$pending" ]; then rm -rf -- "$pending" || :; fi
    if [ -n "$temp" ]; then rm -rf -- "$temp" || :; fi
}
trap cleanup 0
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM
umask 077
temp=$(mktemp -d "$temp_root/dockstride-install.XXXXXX") \
    || fail 'cannot create temporary directory'
package=dockstride-$version-$target
archive=$package.tar.gz
url=$repo/releases/download/$tag
printf 'Downloading Dockstride %s for %s\n' "$tag" "$target"
curl -fsSL -o "$temp/$archive" "$url/$archive" || fail "cannot download $archive"
curl -fsSL -o "$temp/$archive.sha256" "$url/$archive.sha256" \
    || fail "cannot download $archive.sha256"

# Require exactly the checksum entry generated by scripts/release.sh. Never
# allow an untrusted checksum file to name another file or an absolute path.
checksum_line=
lines=0
while IFS= read -r line || [ -n "$line" ]; do
    lines=$((lines + 1))
    [ "$lines" -eq 1 ] || fail 'checksum file must contain exactly one entry'
    checksum_line=$line
done < "$temp/$archive.sha256"
[ "$lines" -eq 1 ] || fail 'checksum file is empty'
hash=${checksum_line%% *}
[ "${#hash}" -eq 64 ] || fail 'invalid SHA-256 checksum length'
case "$hash" in *[!0-9a-f]*) fail 'invalid SHA-256 checksum' ;; esac
[ "$checksum_line" = "$hash  $archive" ] || fail 'checksum filename does not match the release archive'
(CDPATH= cd -P "$temp" && sha256sum -c "$archive.sha256") \
    || fail 'release archive checksum verification failed'

# Read only the expected binary to stdout, so archive paths, links, and sample
# files cannot be written into the destination or the temporary directory.
member=$package/dks
members=$(tar -tzf "$temp/$archive" "$member") || fail 'release archive is missing dks'
[ "$members" = "$member" ] || fail 'release archive must contain exactly one expected dks member'
tar -xzOf "$temp/$archive" "$member" > "$temp/dks" || fail 'cannot extract dks'
chmod 0755 "$temp/dks" || fail 'cannot make downloaded binary executable'
actual=$("$temp/dks" --version) || fail 'downloaded binary cannot report its version'
[ "$actual" = "dks $version" ] || fail "binary version mismatch: expected dks $version, got $actual"

# Stage on the destination filesystem, then rename only after every check.
# A failed download, checksum, extraction, or version check leaves old dks alone.
mkdir -p "$install_dir" || fail "cannot create installation directory: $install_dir"
install_dir=$(CDPATH= cd -P "$install_dir" && pwd -P) || fail 'cannot resolve installation directory'
[ ! -d "$install_dir/dks" ] || fail "destination is a directory: $install_dir/dks"
pending=$(mktemp -d "$install_dir/.dockstride-install.XXXXXX") \
    || fail "cannot stage installation in $install_dir"
cp "$temp/dks" "$pending/dks" || fail 'cannot stage downloaded binary'
chmod 0755 "$pending/dks" || fail 'cannot set installed binary permissions'
mv -f "$pending/dks" "$install_dir/dks" || fail 'cannot atomically install dks'
printf 'Installed Dockstride %s at %s/dks\n' "$tag" "$install_dir"
case ":${PATH:-}:" in
    *":$install_dir:"*) ;;
    *) printf 'PATH hint: add "%s" to your PATH to run dks.\n' "$install_dir" ;;
esac
